# Generated by Django 5.2.4 on 2025-08-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='assignee',
            field=models.CharField(choices=[('A', 'Peter'), ('B', 'Isabelle'), ('BOTH', 'Beide')], max_length=4),
        ),
    ]
